name: Build

 

on:
  push:
    branches:
      - master
  workflow_dispatch:

 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: stable
      - name: Build
        run: |
          flutter build web --release

 